name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_KEY }}
          TARGET_REPO: mizuka-wu/mizuka-wu.github.io
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm ci && npm run build
          BUILD_DIR: .vuepress/dist/
