name: release docs CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: 步骤：第一步 -> Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 步骤：第二步 -> 安装依赖
        run: |
          npm ci
          npm run build
        env:
          CI: true

      - name: 步骤：第三步 -> 使用脚本部署
        env:
          ACCESS_TOKEN_DEPLOY: ${{secrets.DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./.vuepress/dist
          CNAME: www.mizuka.top
        uses: veaba/vuepress-actions@v0.83
